apiVersion: v1
kind: Secret
metadata:
    name: thanos-storage-config
    namespace: monitoring
type: Opaque
stringData:
    object-storage-configs.yaml: ENC[AES256_GCM,data:BM+I9fw6Q9SimqseQc3TF3IGmCWmCwRTRtQzFsGvvX3Yq+paacxeBw/qLIt/I/SqqASMWwxE2U5JrrhB6/Wv5YvT5sHW5kMiogvrBr8r3504ti7dGWv2cZLy1+iobBSXdmNZe+xE9JVihmOu9R067HdqzUCpx97hscAeOVw+89l5c1l9Lf5wvSfP3hKDmO9zHqyy9OMcvnAO+c1ZB7eULDW59nymloEivp0PIErVrsthGuIYQAYuxBJU6jrnx9vZrv0LiqiCUYiE6ua4HHiDNTwFF7xnKorY9pBxwG/ccN0cTiAdTmBqLvCS,iv:T+DYgGjjsuGFxna///JQhhPTrHM/6ciKGr4wcE8Hp3M=,tag:3CB/uJrKtJyk1OzJgZFLSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cWMxUHJVNnNPSTVMTFlK
            ZDg2VnEvM3VucUlmTXYxT3ZSNU1DOWtnRG5vCjJnWmc3aGxHV1lLQUdkc0tWM2d2
            VHVsM2ZCdTN3Y1cwNmxScmtXcDk4MFEKLS0tIDBoTFRGUVJHaVJxS01kZ3BSYXg4
            dzdFb2VxVjVwTExJdWkwWWFMQU4zMmcKmEaOCnYe5xkr7vJjUvQv7kpLMMujvJ23
            K3lHdsgIxszG1+00zD455cfmj+mEDu1JDQ8pXHSNO1URcz+zfxl9Qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T16:46:17Z"
    mac: ENC[AES256_GCM,data:zWJCGu8osFnYOkBGz8fuhUBNCOn6IAEVH+QbzQ9sT8qjLPT9awFkzzZNmj8BzHRH0+MIyVQWGjul/GpH31AgqYn9LIiFfNpqk9UJ6l6ecSnxbjKzaRqUoBikrJzl2w73HANSkf7iaZdnm4kJf15Q8vAbGcqjMJqlxWYmKizzDI0=,iv:JTgTvbWkByJR+fMZFP+xNBlxsDbuMzqRKPlas2MgJlA=,tag:blAzbLYrI0Zko3bDZrauiQ==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml)$
    version: 3.7.1
