apiVersion: v1
kind: Secret
metadata:
    name: thanos-storage-config
    namespace: monitoring
type: Opaque
stringData:
    object-storage-configs.yaml: ENC[AES256_GCM,data:usGbYORPJFid97ai0Wc6TJxz+22n2F0R7kuPk3ci2NhQRURkDI0zcHtMGwH/GYM4O0Ipq4jJRJdnO+eKDQFtalwGEoj6Qnauoyiq64L7V+jVh0wNwxnd9hAd5/F27TI3IkdsjPnJfx10pzAYR1R6oAXZ8pKyP4rrXpc+7lws2aPItu7CZM5c0s6FNYaT6OIDoyxuStJ+4YNUbYTqcSHJcvIEbR22cHySX6ATTRt61qNbQlCVevd89Vy0P7/ebhlGYAAOS72yve3ybPf+TYrgVgPnnAjdL4EGWraflO7y6GShxGh/OqJiJAA05M4spsucAEq7Dn5/N6h6qg==,iv:fLd7LiooJ1hI9Ofd3OkX1a4qP1E0gNEAYWlwP2weYY0=,tag:7Zk4pZG+PeS/MKpmPxyvMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYTc4M1hQTDR1U0FYbkVs
            NFFwS3RoK3BxV2JEZXVqTXhjekRuSWFSN3p3CnpNdGhmam45ajZVaklpb2VYT3ZB
            cjhQazh1cFpOcUNKeHhSeXFxVTNBL2MKLS0tIEZidEw4ZHk2RFZ1UVhaRVU4Zjd5
            LzRGRmlOa29YQ2FSTWE2UGN3V0MxTUUKiL8m44Jmf+6x9ppo/gntwv4FCEvbNblz
            yeKhCWu3QYpHO/I5P5MLHmhybIdE4o9XhXx/vXK9nQf+ixRsgCFBLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T16:51:07Z"
    mac: ENC[AES256_GCM,data:hBCVaXpSOa/K5FezKWf2D+0JCpn3U43VUER5Gnaz0o22HduvqoCJ8FpQFKD0wAY6M6P5N7pDQ8u7F3a3bMOZj2JdJMT6V9yvE5oAj/Ly+5AG4KtLMF4YNegnazqsmG/rjR608eOAVlQvCDgir5EciPJUfV2s3crAuNb8+bNvuGc=,iv:eHZ4QWmsBc526wrf1Kz1uxLdIyXuOLkfVjzJ5GZT8+U=,tag:EWnjEbdxR5gFVu5RUtnxbw==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml)$
    version: 3.7.1
