apiVersion: v1
kind: Secret
metadata:
    name: thanos-storage-config
data:
    object-storage-configs.yaml: ENC[AES256_GCM,data:bhM9KyZzyiSP6osDBOkhDRALpln8ItKoDtjpWk73Z5OnwneuAKwTCjGkxF5E13PkfTGOppf+Ypucfak+dabUK3DfIU4uFh+XbU1RC4ka7YhAilJu2iGUO7JXlymQlZ9YzW/O5/e5SbEURWxf24EumSMhmJVV4Uom3abNzwzF73Tqx667nEV+n7SXptGu5d3YJg47Jj0PbgT9f5ubVyoXvUp4U+WQwjRNysSq681elFu5MQVrXQpq0ix8u5KZ28zqgd1jNaPUCUNc9FmSNbzsnsx0kzB3S503yQyfoIVNTLmKA7XAJyH4MzgjGovVIhDZrNWJgQwSnbR/AZH8cIp5bFlpLmFSzER8bymeFmjRpo6zv7oQERCqhQv+OCY4jPK/NmvcGJVQS8rYOPByai1qf4rWqiQYuXzpTpqFqOetbKCgiVxZVpcmQ8OijIFtKXsDpG9Dz9YUWSSWWYfJxT+8fIoc52adJMG8WqudkeCT5JVi2xrWCx3eLW6/elrtbveK8/sW+lcq5UunfAs0AUfDYgQoOVyoCQTimPXwccajO85bfHh8A+XYl4AmGkfH58gyXM21gYZ4LeHHCixHFRRGHY9nyOjUNKdmNFK06cmjZT+lNgna8GfXTIc3UY22ikRpwI4BfQaldIgbFdaBhIKb/aRkB5S/UXvqpsghLKX+axEKGeFOnFl9F88zvLLAaQm85z/IUWTW+uxzkfUnjJ/4+bCwrHWRRK0cJTyDZF3hpvIq8qEXbokOTg==,iv:0IR/I69ZiF03b3Hcwc3Gr1oKTvLe6jX5t4V2ZLsOzwE=,tag:QsAjo51xwSTYhFmYcddVmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWC9adTRSbmRoMThHcndx
            MS8ydnB3bWpYNzErOFViblM5NjBlbXR6dUhBCmxwY3ZvdGhLQU1QbkRIL0wvNHFo
            eGN3ZS9EaDgrWnVHd01rakpkam1TcFUKLS0tIHJxWXhjZTM3ZldjeEpaZVFHcGVs
            bVcwYlluaVVkL0VDVU50QlYxSVBBQ2MKTuXUex/Q67hyeNGT5bU9W4xIUtSGPLtz
            DJMqr2NBaFDOvc/wIU9lJLrs87uYaG5IPtDEXNxxltffJjQ2fNxyFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T17:45:07Z"
    mac: ENC[AES256_GCM,data:ARz6ilhkJNyPlRurGzjQoy3o60l0iZ01Uk8rkqQaUS3GNmOX7gD4n5SUMXNpEmZt7j6Gt2TdxRiGxsxG33RuJMi4MEqKgGdbIazDfJcpLZ1loPwWz5bIpwZjNwjNdxXa1IDTWVlFZcruG0PyyQXPupvLJKBYlvu4fz6EmkHiV8M=,iv:yS+MLlMD31QbczAL3kk97gB1CY0i5lgSlAKUpKVwfdI=,tag:OPhXA/m+pPqkT7LDaZLlWA==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml)$
    version: 3.7.1
