apiVersion: v1
kind: Secret
metadata:
    name: thanos-storage-config
    namespace: monitoring
type: Opaque
stringData:
    object-storage-configs.yaml: ENC[AES256_GCM,data:ddbNiChAqmsnV0p8pf+kKrgc075mAtaExy3sgfxAmFK0yKs6LSVK6gOXOf0804FF3PG80fkWzC0cl5ek6XXw1eu7wSU2Lp3CEBqLbQnxMYTGLQrLpHQYgJKcr1WidieT4XWPcP7E3+GiMu/J+hFFZkHmAusgBuN/q7q0QnhkJ8lMlaBzZE7g9JJVFK2uudpfu/VhaR4RN6hV/6+mYVu6wbv5RlDSkrY4RZmOUYCVL7HBzNv78usm5CtCWryVgiHLyuBXMxtAxe3VrcXbOKDg2HGAnwNCgqEFP37//EQxT1TkEEgi33H45HY5U5UrCpeFnnD9watPGwRkWno=,iv:pfYoXbSuFi/0oj1gBxBg8CHBL/BQhBbnD5F+Bn2+6Ok=,tag:ws7NaacQomxlF409FUrOxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQkNQSVFmUFV2UENsUm1s
            YndiQk02OHFWZFdSWU9YS0tTTVMvZy9Bd0ZrCkQxb0MwWTNENkpkdTJ0bzg4a0dT
            ZHJDRHZvQmxCS09QMHJ3b29sR1pvSk0KLS0tIGRJUTJWUm5uK2F4M1dRNFZuUEZx
            cEVkY3RTR1p6U2xPUGRUQzJXaFUwSnMKtHpS7rIehireVfidfukAclfKmfNODkcB
            lNq79B/6LC8/3lCoqtj7yZ5YzTThr8HHwzNbHzuyGBg3UJxR/mtViw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T16:53:43Z"
    mac: ENC[AES256_GCM,data:kAKgn8MoyfP1wlGkwIYXb/U0TmabLD8yWhr1GlkayZOjZSzjR1wWxr1n6eJ0fV+9vtsB/CGpnTrU5UmEy7+PQXqrdnZhkXIgKoXRoormqmdULrWExhICM04HhINYkzmcTdAU/+yiDuwy8Z1hUYqPGOQTg0+C3Vu6oWEWWhbjYvY=,iv:OL74nbQu+YmaBpbFDPqnUsPAjCs1QkFzRKniS/280zE=,tag:QBGT4dplc2dvBFKBYfaioQ==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml)$
    version: 3.7.1
