apiVersion: v1
kind: Secret
metadata:
    name: thanos-storage-config
    namespace: monitoring
type: Opaque
stringData:
    object-storage-configs.yaml: ENC[AES256_GCM,data:oMf/e4+3bKkwL4U5oAHZGwnqdhg5MfXJhAxHccaZqvsfLRvIqvYOTzBDtPBiXBoenKMaJVfi9WjWs9PWmcxq+81+tncHJOog6KffbAUL38Dj30zKG71T0QgadnvBZdMT8TizFF52qHEt7m3FcgPAkTyE9fbeyLChb33GEiNAkyz5ixlmzLln0Tk46ukGYFYEyolKxh6AS478XBjeVChYKWAk6zUCmysBnFViaOqNb7UWrSfcUYAVkPBSEZuhUNe1o3m7KIMlJm8S7zXPypg1kB0fLOE8,iv:nhlnjSjN+20aZGClD27ZBsxXYnuO7j5NiXKeLi/Oh5I=,tag:696sa5fuisW60Ir7k+7Bnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMHBnbHM2V2tvT2Zob3Fx
            VG92VkJWVVBVby9pcDRNeGpZVE9XVzM3bEdrCjhzL0hoQWk3WURVVkdEdU5MaDdB
            VDBqcWgydWczbkN1cXIwQVVQWlltdXMKLS0tIHJMVENqeGpqNjNET3FiQ1pvMzJi
            ajFZcEhjT0JaT3V4UEp5Q3FmK3BtUDQKn6P7TmN7Y23/JgKTTZcV0oZvunJjOva0
            BKoROItInbx0s2u3pYNmmPf42J95RoeIFJ7/pXZm8GDJABzP6FhxPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T16:34:40Z"
    mac: ENC[AES256_GCM,data:mCk6VfAqJCI/bJFqDgbeweh9rlhMIUu4avzTBWJS02f4Lfgjn5mTpFpkGYxUDyTqsPK6zVLIH61HgwCY8sylmKKiSzFdPd2yxTz2ClnMBNT/0LUGEp9AEXf/aRvVzTmae4Bc8VyGB33e5TogkReNh7GSXx8xwVOFLCSw5Qaam8k=,iv:jhPCWOBb4CvyNFbUx5/tK+nLhMU8EymNtFfiJ5aWSI0=,tag:yVZigmtsEhjPEBqKlky0gQ==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml)$
    version: 3.7.1
