apiVersion: v1
kind: Secret
metadata:
    name: thanos-storage-config
data:
    object-storage-configs.yaml: ENC[AES256_GCM,data:UZOrkxbW4RM0JBmeMSYV7kOAdEVxCNyokY3tWqsDUSYX3LpjbGkdID6GUNQ46zGIDL1z68wHrw/Ce5ihBGXJR8bZ5qjC54XB/6YmxGl5CHrrBmlOCX5iPmzjXywShHQhUj54laoA9R8y3zI4FnLvSu7pfAQdYeMlFGzTmr93wo3ibqvkRz1idE2BaKflJvgdnexqxxkozUDt/UpMaoMGduvJVpfu6kfVR7HfsHNMmJMzrnDlXRDA9tLfY4OLQXlRvQY0stQ5Xzv2wwejLAmKUttiiz7lawRsaJDP2lJGc2W0oO0HpqibjrUIPcIUm/gEx+JwPpBEcG3tl7Mz4FW5ZfVkTTQkctFzOPLEFfYjp2FbRy+2GfA5/1l7EBoxr04zDjTsjAUXXFI7HojLtTeGlib8sTihuUyc0Jo8C3jNHS/7tNnQMAYttCAz0bp7LEkRKCNMrzn2Jvo9F+aXKUDhBOmXwt0YfOE1,iv:moTTVMdc8Q81WpqYbGtrQXWmM0kY7YDt6xFNepbtgG8=,tag:s60pxnvWXQCwJIFbuUZ3zQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WkRZZWM5dWpwRTRrYWtM
            eTQwa1M5S2pCZ0VLdGZQdkNWSkhHcVd6V1U4ClBmMHU1dFFGMmRvV3ovQXZHWHY3
            MCtXcWtydGdCQ3BrQ3F3SzVQbDFlN2cKLS0tIEg1N05FM0VZREtDZ05LVnR3eFhy
            RXkvWHN3NWxHcU5GYkd5ck1xWFlWbDgK3QngPw9rDTjrf0+zgu/JyRdsoqKAlkDt
            a7QBzN2Mo3+BVZbVi9w6ED5KyWr73u1g2lEHg+Qcelmx2hS30gK4OQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T18:41:44Z"
    mac: ENC[AES256_GCM,data:NuXQJWCBE4THarSrNmUzZmHvutJIMe/EhCPpOB85TyB8Q85UNzP7FzrXAoOVtsNKL20UkKNn0PT7vheoCw2k7hnQ52KEygFIpWf8/CeESFvZUsWduwK8Kpz+LQVZ4FsQTx12GueM+1cgK3k1HP5pWsUi+rgFAfq7QcRMMurFapk=,iv:py0r6SBCEbdtrdQmDv03XBSycU0zqEGW0vSIO2AZ8d8=,tag:czhAKSdDeaA+eZy1K7WoCQ==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml)$
    version: 3.7.1
