apiVersion: v1
kind: Secret
metadata:
    name: thanos-storage-config
    namespace: monitoring
type: Opaque
stringData:
    object-storage-configs.yaml: ENC[AES256_GCM,data:y9eZpNE9HlwXl7y8Gd8iKCtj1tze4oVoWQc1ofarqhMEG7DMMBWwXXi1qCQLVVe05+JdyNNBQz4gSaDNGrfwCAKfMyNiQ4amDxXvAeDy29xF+Ru/J09zdz/cB8QGl2+yo2xbUY/R7WL1np2LDpNXwCSpq/P0Zntt5P4IcOiFUFqmZIwrvyUJBmIVEs/44jXY8W7+C6RgtBCgH8YBRuFPrcMpLZCOKIRDSI6tOGySZwrxRNkQTJX9uIfTBi6Z8jDMZ+dRhjhzR4t23yqVjw==,iv:/plgUnyF+NP0ALHSJv8bZD/mEKX1ziIUSSX1+irMrjk=,tag:18hgD8A6OmetF6LFbTjKSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wp7n5rlrjdqjx7hpkfv35ejwauuggyncl0cu4zllcq59a696sudqnucqfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dUphMFgrdlFYNHJRTVNI
            aHlFSlZoMFJkY2J5dll4NnNFODF5eXF6NFVJCmxOZFZvcW4rMkJnek5SVFdFWHBm
            SGhYQkhwM0RIVEovZWI4dGpsNkJMbW8KLS0tIHpvVTJWM3gzQk5aRE4xMGZ2Mk1l
            SllDbDZpNkVnOFE2WkVYRmZaSmlMZEUKub6suQzg6x2C0/oZL1lV5TKBNjejaHfm
            ABbkkonkoFQazJhCo0lFSLmDBw0JbnO9yBRm0nVHFAh9kEf4oBnXtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T16:42:45Z"
    mac: ENC[AES256_GCM,data:jr8tdyGumEpzmpJ3lxU9ZxR6Bd2aiMN4cowFPhp6m8hzb/GUs+OiD+/Ks+2KpcUXZN+N4xWMA/5PQ2rATtz6iIFW8nly0Td/NVo43TUSzG3DXXw/2sZKDPDi7v1ymNQrpEm+WU2VzcSDqiM+ARZKscV+LGEdLCnnqGd02qI1NP4=,iv:NnmTotzj/SJvlHMywk25Ozk4Ao6tYgTndPzzxcY7UiQ=,tag:deBQ+7rPt38KO5/WSpgjag==,type:str]
    pgp: []
    encrypted_regex: ^(SOPS_AGE_KEY|.*password.*|.*PASSWORD.*|.*Secret.*|email|.*USERNAME.*|MIKROTIK_BASEURL|access-token|unseal_keys.*|vault-init.yaml|object-storage-configs.yaml)$
    version: 3.7.1
