---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ../../base/components.yaml


patches:
  - patch: |-
      # Use JSON Patch syntax to add an item to the args array
      # The path points to: spec -> template -> spec -> containers (first container, index 0) -> args
      # The "-" at the end of the path means "add element to the end of the array"
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kubelet-insecure-tls
    target:
      kind: Deployment
      name: metrics-server
      namespace: kube-system
      version: v1
